site_name: Terraform Provider OCI Copy
site_url: https://ascopes.github.io/terraform-provider-oci-copy
site_author: ascopes
site_description: >-
  Preview for the Terraform Provider documentation.
theme:
  features:
    - content.code.copy
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
  name: material
  palette:
    accent: purple
    primary: deep-purple
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences