name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build the provider
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Determine Go Version
      run: echo "GO_VERSION=$(< .go-version)" >> "${GITHUB_ENV}"

    - name: Configure Golang
      uses: actions/setup-go@v4
      with:
        check-latest: true
        go-version: "${{ env.GO_VERSION }}"

    - name: Run tests
      run: make test
