name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build the provider
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Configure Golang
      uses: actions/setup-go@v4
      with:
        check-latest: true
        go-version: "^1.20.0"
    
    - name: Download dependencies
      run: make download
    
    - name: Build provider
      run: make build

    - name: Run tests
      run: make test
