name: Generate GitHub Pages

on:
  push:
    branches:
      - "main"

jobs:
  pages:
    name: Generate GitHub Pages documentation
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Determine Go Version
      run: echo "GO_VERSION=$(< .go-version)" >> "${GITHUB_ENV}"

    - name: Configure Golang
      uses: actions/setup-go@v4
      with:
        check-latest: true
        go-version: "${{ env.GO_VERSION }}"

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        check-latest: true
        python-version: "^3.11"

    - name: Generate documentation
      run: make docs

    - name: Upload Site
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site
    
    - name: Deploy uploaded documentation
      id: documentation
      uses: actions/deploy-pages@v2
